roles:
# Install a role from Ansible Galaxy.
  - name: junipernetworks.junos
    version: "5.1.0" # note that ranges are not supported for roles

collections:
# Install a collection from Ansible Galaxy.
  - name: junipernetworks.junos
    version: ">=5.0.0"
    source: https://galaxy.ansible.com
  - name: juniper.device
    version: ">=1.0.2"
    source: https://galaxy.ansible.com
  - name: community.general
    version: ">=6.6.0"
    source: https://galaxy.ansible.com