---
- name: Gather ge-0/0/0 interface information
  hosts: 
    - all
  connection: local
  gather_facts: no
  tasks:
    - name: Gather ge-0/0/0 interface information
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces ge-0/0/0
        provider:
          port: 22
          user: "{{ username }}"
          passwd: "{{ password }}"
        waitfor:
          - "result[0].interface-information.physical-interface.name eq ge-0/0/0"
      register: result

    - debug: var=result.stdout
