---
- name: Get Subscriber and Interface Data
  hosts:
    - all
  connection: local
  collections:
    - juniper.device
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"

  tasks:
    - name: "Get facts"
      juniper.device.facts:
      register: response
    - name: "yeet"
      debug:
        var: response.ansible_facts.junos.config