---
- name: Get Subscriber and Interface Data
  hosts:
    - all
  connection: local
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"

  tasks:
    - name: Retrieve Interface Infos
      juniper.device.rpc:
        rpcs: get-interface-information
        kwargs:
          - terse: True
      register: result

    - name: Print Interface Infos
      debug:
        var: result.parsed_output

    - name: Install jmespath
      ansible.builtin.pip:
        name:
          - jmespath>=1.0.0
      register: pytpack

    - name: Filter through Interface Data
      when: pytpack
      ansible.builtin.debug:
        var: item
      loop: "{{ result.parsed_output | community.general.json_query('interface_information.physical_interface[*].name') }}"