---
- name: Get Subscriber and Interface Data
  hosts:
    - all
  connection: local
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"

  tasks:
    - name: Retrieve device facts and configuration and save facts to file
      juniper.device.rpc:
        rpcs: get-interface-information
      register: result

    - name: Print configuration
      debug:
        var: result
