---
- name: Get Subscriber and Interface Data
  hosts:
    - all
  connection: local
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"
  collections:
    - juniper.device

  tasks:
    - name: "Get facts"
      facts:
      register: response