---
- name: Get Subscriber and Interface Data
  hosts:
    - all
  connection: local
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"

  tasks:
    - name: Retrieve Interface Infos
      juniper.device.rpc:
        rpcs: get-interface-information
        kwargs:
          - terse: True
      register: rpc_reply

    - name: Print Interface Infos
      debug:
        var: rpc_reply.parsed_output

    - name: Install jmespath
      ansible.builtin.pip:
        name:
          - jmespath>=1.0.0
      register: pytpack

    - name: Filter through Interface Data
      when: pytpack is changed
      ansible.builtin.debug:
        var: rpc_reply
      loop: "{{ result | community.general.json_query('rpc_reply.parsed_output.`interface-information`') | list }}"