---
- name: Get Subscriber and Interface Data
  hosts:
    - all
  connection: local
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"
  collections:
    - juniper.device.facts

  tasks:
    - name: "Get facts"
      register: response
    - name: "yeet"
      debug:
        var: response.ansible_facts.junos.config